name: Autograding

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Generate test report
      if: always()
      run: |
        ./gradlew test --info
        echo "Test Results Summary:"
        if [ -f build/test-results/test/TEST-*.xml ]; then
          echo "Tests completed. Check the test report for details."
        fi
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/test-results/test/
    
    - name: Comment PR with results
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Read test results
          let message = '## 🧪 Test Results\n\n';
          
          if (${{ job.status }} === 'success') {
            message += '✅ **All tests passed!**\n\n';
            message += 'Great job! Your implementation meets all requirements.\n';
          } else {
            message += '❌ **Some tests failed.**\n\n';
            message += 'Please review the test output and fix the failing tests.\n';
            message += 'Run `./gradlew test` locally to see detailed error messages.\n';
          }
          
          // Comment on PR
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
    
    - name: Check code quality
      run: |
        echo "Code quality check would run here (SonarCloud integration)"
        echo "For now, just checking that code compiles"
        ./gradlew build