name: Java CI with Gradle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Run tests
      run: ./gradlew test --no-daemon

    - name: Generate JaCoCo coverage report
      run: ./gradlew jacocoTestReport --no-daemon

    - name: Verify code coverage
      run: ./gradlew jacocoTestCoverageVerification --no-daemon

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jacoco-reports
        path: build/reports/jacoco/test/html/

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: build/reports/tests/test/
